# Generated by Django 5.1 on 2024-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='valueDecimal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
