# Generated by Django 5.1 on 2024-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_discount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
