# Generated by Django 5.1 on 2024-09-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpcode_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otpcode',
            unique_together={('phone_number', 'code')},
        ),
    ]
